spring:
  application:
    name: ms-security
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /security
  port: 9085


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
